config/routes.rb
Zap::Engine.routes.draw do

  resources :users do
    resources :permissions
    resources :assets
    resources :activities
    resources :comments
    resources :properties
    resources :tags
  end
  resources :spaces do
    resources :permissions
    resources :assets
    resources :activities
    resources :comments
    resources :properties
    resources :tags
  end
  resources :audits
  resources :assets

  match "/auth/:provider/callback" => "sessions#create"
  match "/logout" => "sessions#destroy", :as => :logout
  match "/login" => "sessions#new", :as => :login
  root :to => 'audits#index'
end

app/models/zap/activity.rb
class Zap::Activity < ActiveRecord::Base
  set_table_name 'activities'
  belongs_to :user

  validates :action, :presence => true
  validates :resource_class, :presence => true
  validates :resource, :presence => true
  
  def self.register(controller, user)
    action = controller.request.params[:action]
    if action == 'create' or action == 'update' or action == 'destroy'
      model_id = action == 'create' ? nil : controller.request.params[:id]
      Zap::Activity.create(:action => action, :resource_class => controller.send(:resource_class), :resource_id => model_id, :user_id => user.id)
    end
  end

end

app/models/zap/asset.rb
class Zap::Asset < ActiveRecord::Base
  set_table_name 'assets'
  belongs_to :user
  belongs_to :space
  mount_uploader :locator, Zap::AssetUploader
  
  validates :name, :presence => true
  validates :user, :presence => true
  validates :space, :presence => true
  
end

app/models/zap/asset_uploader.rb
module Zap
    class AssetUploader< CarrierWave::Uploader::Base
        storage :s3
        def store_dir
            "booka/#{mounted_as}/#{model.id}"
        end

        def cache_dir
            "#{Rails.root}/tmp/uploads"
        end
    end
end

app/models/zap/audit.rb
class Zap::Audit < SimpleAudit::Audit
  set_table_name 'audits'
end

app/models/zap/authorization.rb
class Zap::Authorization < ActiveRecord::Base
  set_table_name 'authorizations'
  belongs_to :user

  validates :user_id, :presence => true
  validates :provider, :presence => true
  validates :uid, :presence => true
  validates_uniqueness_of :uid, :scope => :provider

  def self.find_from_auth(hash)
    find_by_provider_and_uid(hash['provider'], hash['uid'])
  end

  def self.create_from_auth(hash, user = nil)
    user ||= Zap::User.find_or_create_from_auth!(hash)
    Zap::Authorization.create(:user => user, :uid => hash['uid'], :provider => hash['provider'])
  end
end

app/models/zap/comment.rb
class Zap::Comment < ActiveRecord::Base
  set_table_name 'comments'
  belongs_to :user
  belongs_to :space
  belongs_to :resource, :polymorphic => true

  validates :space_id, :presence => true
  validates :resource_id, :presence => true
  validates :resource_type, :presence => true


  def self.new_for(resource)
    self.new(:resource_id => resource.id, :resource_type => resource.class.to_s)
  end
end

app/models/zap/permission.rb
class Zap::Permission < ActiveRecord::Base
  set_table_name 'permissions'
  belongs_to :user
  belongs_to :resource, :polymorphic => true
  
  LEVELS = [:read, :write, :manage]

  validates :user, :presence => true
  validates_uniqueness_of :user_id, :scope => [:resource_id, :resource_type]
  validates :resource_id, :presence => true
  validates :resource_type, :presence => true
  validates :level, :presence => true
  
  def self.new_for(resource)
    self.new(:resource_id => resource.id, :resource_type => resource.class.to_s)
  end
end

app/models/zap/space.rb
class Zap::Space < ActiveRecord::Base
  set_table_name 'spaces'
  acts_as_taggable
  simple_audit :except => [:created_at, :updated_at]

  has_many :permissions, :foreign_key => :resource_id, :conditions => "resource_type = 'Zap::Space'"
  has_many :users, :through => :permissions, :source => :resource, :source_type => "User",
      :conditions => "permissions.resource_type = 'User'"
  has_many :comments, :foreign_key => :resource_id, :conditions => "resource_type = 'Zap::Space'"
  has_many :assets

  validates :name, :presence => true
  
  def parent_id
    self.id
  end
end

app/models/zap/user.rb
class Zap::User < ActiveRecord::Base
    include SentientUser
    acts_as_tagger
    
    set_table_name 'users'
    simple_audit :except => [:created_at, :updated_at]

    has_many :authorizations
    has_many :permissions
    has_many :spaces, :through => :permissions, :source => :resource, :source_type => "Space",
      :conditions => "permissions.resource_type = 'Space'"
    has_many :audits

    validates :email, :presence => true, :uniqueness => true
    validates :name, :presence => true

    after_create :create_admin

    def super?
        roles == 'admin'
    end

    def self.find_or_create_from_auth!(hash)
        user_info = hash['user_info']
        user = find_by_email(user_info['email'])
        user = create(:name => user_info['name'], :email => user_info['email']) unless user
        user
    end

    protected

    def create_admin
        self.update_attribute(:roles, 'admin') if self.id == 1
    end
end

app/controllers/zap/admin_controller.rb
class Zap::AdminController < ApplicationController
  layout 'zap/admin'
  include Zap::AuthModule
  helper_method :current_user
  helper Zap::ZapHelper, Zap::ActionsHelper, Zap::RenderHelper
  self.responder = Zap::ZapResponder
  respond_to :html, :xml, :json
  before_filter :require_admin
  before_filter do |c|
    Zap::User.current = c.send(:current_user)
  end
  
  def resource_class
    self.class.name[0..-12].constantize
  end
end

app/controllers/zap/application_controller.rb
module Zap
  class ApplicationController < ActionController::Base
  end
end

app/controllers/zap/assets_controller.rb
class Zap::AssetsController < Zap::AdminController
  respond_to :html, :xml, :js
  before_filter :load_sources
  def index
    @assets  = Zap::Asset.all
    respond_with @assets
  end

  def new
    @asset = Asset.new(:space => @space, :user => @user)
  end

  def create
    @asset = @source.assets.build(params[:asset])
    flash[:notice] = "Fichero subido" if @asset.save
    redirect_to @source
  end

  def edit
    @asset = @source.assets.find params[:id]
  end

  def update
    @asset = @source.assets.find params[:id]
    @asset.update_attributes(params[:asset])
    if @asset.save
      flash[:notice] = "Fichero actualizado"
      redirect_to @source
    else
      render :action => 'edit'
    end
  end

  protected

  def load_sources
    @source = @space = Space.find(params[:space_id]) if params[:space_id]
    @user = User.find params[:user_id] if params[:user_id]
  end
end

app/controllers/zap/audits_controller.rb
class Zap::AuditsController < Zap::AdminController

  def index
    @audits = Zap::Audit.all
  end
end

app/controllers/zap/auth_module.rb
module Zap::AuthModule
  protected
  def current_user
    @current_user ||= Zap::User.find_by_id(session[:user_id])
  end

  def require_user
    unless current_user
      store_location
      redirect_to login_path
    end
  end

  def require_admin
    unless current_user
      store_location
      redirect_to login_path
    end
  end

  def store_location
    session[:return_to] = request.fullpath
  end

  def stored_or(default_path)
    path = session[:return_to] || default_path
    session[:return_to] = nil
    path
  end

  def signed_in?
    !!current_user
  end

  def clear_user
    @current_user = nil
    session[:user_id] = nil
  end

  def current_user=(user)
    @current_user = user
    session[:user_id] = user.id
  end
end

app/controllers/zap/comments_controller.rb
class Zap::CommentsController < Zap::AdminController
  before_filter :load_source
  
  def index
    @comments = @source.comments
  end
  
  def new
    @comment = Comment.new_for(@source)
    respond_with @comment
  end

  def edit
    @comment = @source.comments.find params[:id]
    respond_with @comment
  end

  def show
    redirect_to @source
  end

  def create
    @comment = @source.comments.build(params[:comment])
    @comment.space_id = @source.parent_id
    if @comment.save
      flash[:notice] = 'Comentario creado'
      redirect_to @source
    else
      render :action => 'new'
    end
  end

  def update
    @comment = @source.comments.find(params[:id])
    @comment.update_attributes(params[:comment])
    @comment.save
    redirect_to @source
  end

  protected

  def load_source
    @source = User.find params[:user_id] if params[:user_id]
    @source = Space.find params[:space_id] if params[:space_id]
  end

end

app/controllers/zap/info_controller.rb
module Zap
  class InfoController < ApplicationController
    def index
      render :text => 'simpole'
    end
  end
end

app/controllers/zap/permissions_controller.rb
class Zap::PermissionsController < Zap::AdminController
  before_filter :load_source
  def new
    @permission = Permission.new_for(@source)
    respond_with @permission
  end

  def edit
    @permission = @source.permissions.find params[:id]
    respond_with @permission
  end

  def show
    redirect_to @source
  end

  def create
    @permission = @source.permissions.build(params[:permission])
    if @permission.save
      flash[:notice] = 'Permiso creado'
      redirect_to @source
    else
      render :action => 'new'
    end
  end

  def update
    @permission = @source.permissions.find(params[:id])
    @permission.update_attributes(params[:permission])
    @permission.save
    redirect_to @source
  end

  protected

  def load_source
    @source = User.find params[:user_id] if params[:user_id]
    @source = Space.find params[:space_id] if params[:space_id]
  end

end

app/controllers/zap/sessions_controller.rb
class Zap::SessionsController < ApplicationController
  layout 'zap/admin'
  helper Zap::ZapHelper
  include AuthModule
  helper_method :current_user

  def new
  end

  def show
  end

  if Rails.env == :test
    def enter
      self.current_user = Zap::User.find(params[:id])
    end
  end


  def create
    auth = request.env['rack.auth']
    unless @auth = Zap::Authorization.find_from_auth(auth)
      @auth = Zap::Authorization.create_from_auth(auth, current_user)
    end
    self.current_user = @auth.user

    redirect_to stored_or(root_path)
  end

  def destroy
    self.clear_user
    redirect_to root_path
  end
end

app/controllers/zap/spaces_controller.rb
class Zap::SpacesController < Zap::AdminController
  respond_to :html, :xml, :json
  #after_filter { |controller| Zap::Activity.register(controller, current_user) }

  def index
    @spaces = Zap::Space.all
    respond_with @spaces
  end

  def show
    @space = Zap::Space.find params[:id]
    respond_with @space
  end

  def new
    @space = Zap::Space.new
    respond_with @space
  end

  def create
    @space = Zap::Space.new(params[:space])
    @space.save
    respond_with(@space)
  end

  def edit
    @space = Zap::Space.find params[:id]
    respond_with @space
  end

  def update
    @space = Zap::Space.find(params[:id])
    @space.update_attributes(params[:space])
    respond_with(@space)
  end
end

app/controllers/zap/users_controller.rb
class Zap::UsersController < Zap::AdminController
  respond_to :html, :xml, :js

  def index
    @users = Zap::User.all
    respond_with @users
  end

  def show
    @user = Zap::User.find params[:id]
    respond_with @user
  end

  def new
    @user = Zap::User.new
    respond_with @user
  end

  def create
    @user = Zap::User.new(params[:user])
    @user.save
    respond_with(@user)
  end

  def edit
    @user = Zap::User.find params[:id]
    respond_with @user
  end

  def update
    @user = Zap::User.find(params[:id])
    @user.update_attributes(params[:user])
    respond_with(@user)
  end

  def destroy
    @user = Zap::User.find(params[:id])
    @user.destroy
    redirect_to users_path
  end
end

app/views/layouts/zap/admin.html.erb
<!doctype html>
<!-- paulirish.com/2008/conditional-stylesheets-vs-css-hacks-answer-neither/ -->
<!--[if lt IE 7 ]> <html lang="en" class="no-js ie6"> <![endif]-->
<!--[if IE 7 ]>    <html lang="en" class="no-js ie7"> <![endif]-->
<!--[if IE 8 ]>    <html lang="en" class="no-js ie8"> <![endif]-->
<!--[if (gte IE 9)|!(IE)]><!--> <html lang="en" class="no-js"> <!--<![endif]-->
  <head>
    <meta charset="utf-8">
    <meta name="csrf-token" content="<%= form_authenticity_token %>" />
    <!-- Always force latest IE rendering engine (even in intranet) & Chrome Frame
         Remove this if you use the .htaccess -->
    <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">

    <!-- encoding must be specified within the first 512 bytes www.whatwg.org/specs/web-apps/current-work/multipage/semantics.html#charset -->

    <!-- meta element for compatibility mode needs to be before all elements except title & meta msdn.microsoft.com/en-us/library/cc288325(VS.85).aspx -->
    <!-- Chrome Frame is only invoked if meta element for compatibility mode is within the first 1K bytes code.google.com/p/chromium/issues/detail?id=23003 -->


    <title><%= yield :title %></title>
    <meta name="description" content="Recortable">
    <meta name="author" content="danigb">

    <!--  Mobile viewport optimized: j.mp/bplateviewport -->
    <meta name="viewport" content="width=device-width, initial-scale=1.0">


    <link href='http://fonts.googleapis.com/css?family=Ubuntu' rel='stylesheet' type='text/css'>

    <!-- Place favicon.ico & apple-touch-icon.png in the root of your domain and delete these references -->
    <link rel="shortcut icon" href="/favicon.ico">
    <link rel="apple-touch-icon" href="/apple-touch-icon.png">


    <!-- CSS : implied media="all" -->
    <link rel="stylesheet/less" href="/zap/stylesheets/admin.less" type="text/css">

    <!-- Uncomment if you are specifically targeting less enabled mobile browsers
    <link rel="stylesheet" media="handheld" href="css/handheld.css?v=2">  -->

    <!-- All JavaScript at the bottom, except for Modernizr which enables HTML5 elements & feature detects -->
    <script src="/zap/javascripts/less-1.0.41.min.js"></script>
    <script src="/zap/javascripts/modernizr-1.6.min.js"></script>
  </head>

  <body>
    <div id="container">
      <% if flash[:notice].present? %>
        <div class="flash notice">
          <%= flash[:notice] %>
        </div>
      <% end %>
      <div id="session">
        <% if current_user %>
          <%= link_to current_user.name, current_user %> |
          <%= link_to t('zap.actions.logout'), logout_path %>
        <% else %>
          <%= link_to t('zap.actions.login'), login_path %>
        <% end %>
      </div>
      <div class="container main">
        <div id="sitebar">
          <% if current_user %>
            <ul>
              <li class="top"><%= link_to 'Users', users_path  %></li>
              <li class="top"><%= link_to 'Spaces', spaces_path  %></li>
              <li class="top"><%= link_to 'Ficheros', assets_path  %></li>
              <li class="top"><%= link_to 'Actividad', audits_path  %></li>
              <li class="top"><%= link_to 'Mailing', audits_path  %></li>
              <li class="top"><%= link_to 'Invitaciones', audits_path  %></li>
              <li class="top"><%= link_to 'Eventos', audits_path  %></li>
            </ul>
          <% end %>
        </div>
        <div id="page">
          <%= yield %>
        </div>
      </div>
      <div id="legal"></div>
    </div> <!--! end of #container -->


    <!-- Javascript at the bottom for fast page loading -->

    <!-- Grab Google CDN's jQuery. fall back to local if necessary -->
    <script src="//ajax.googleapis.com/ajax/libs/jquery/1.4.4/jquery.js"></script>
    <script>!window.jQuery && document.write(unescape('%3Cscript src="/zas/javascripts/libs/jquery-1.4.4.js"%3E%3C/script%3E'))</script>


    <!-- scripts concatenated and minified via ant build script-->
    <script src="/zap/javascripts/rails.js"></script>
    <script src="/zap/javascripts/plugins.js"></script>
    <script src="/zap/javascripts/scripts.js"></script>
    <!-- end concatenated and minified scripts-->


    <!--[if lt IE 7 ]>
      <script src="js/libs/dd_belatedpng.js"></script>
      <script>DD_belatedPNG.fix('img, .png_bg'); // Fix any <img> or .png_bg bg-images. Also, please read goo.gl/mZiyb </script>
    <![endif]-->


    <!-- mathiasbynens.be/notes/async-analytics-snippet Change UA-XXXXX-X to be your site's ID -->
    <script>
      var_gaq=[['_setAccount','UA-XXXXX-X'],['_trackPageview']];
      (function(d,t){var g=d.createElement(t),s=d.getElementsByTagName(t)[0];g.async=true;
        g.src=('https:'==location.protocol?'https://ssl':'http://www')+'.google-analytics.com/ga.js';
        s.parentNode.insertBefore(g,s)})(document,'script');
    </script>

  </body>
</html>